#!/bin/sh

SELF_DIR="$(dirname "$(readlink -f "$0")")"
LIBS_PATH="$SELF_DIR/usr/lib:$SELF_DIR/usr/lib/x86_64-linux-gnu"

LD_LIBRARY_PATH="$LIBS_PATH:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH

echo $LD_LIBRARY_PATH
exec "$SELF_DIR/usr/bin/disasterlauncher"